### ISSUE TITLE
Dangling commas

### ISSUE THREAD

**Issue by jhnns** [peerigon/eslint-config-peerigon#10]
I would like to change our linting rules to enforce [dangling commas](http://eslint.org/docs/rules/comma-dangle) in multiline literals, likes this:

```js
{
    a: 1,
    b: 2,
}

[
    1,
    2,
]

import {
    a,
    b,
} from "bla";
```

**Why?**

1. Moving items up and down becomes easier, because we don't need to care about adding or removing commas
2. Cleaner diffs
3. Valid ES3 syntax (!). The only reason why people didn't do it is because IE8 threw a SyntaxError
4. Community support: The [Airbnb linting rules](https://github.com/airbnb/javascript/blob/772bbb5b7d2f6990e519c3d70539f807257492fe/packages/eslint-config-airbnb-base/rules/errors.js#L4-L10) do also enforce it
5. Easy update via `--fix`

**Why not optional?**

Because we should stick to one style. We wouldn't really have benefit 1. and 2. if it is optional.

The rule would be configured like this:

```js
        "comma-dangle": ["error", {
            arrays: "always-multiline",
            exports: "always-multiline",
            functions: "ignore",
            imports: "always-multiline",
            objects: "always-multiline",
        }],
```

Any objections? @peerigon/everyone

**Comment by acidicX** [comment]
> Moving items up and down becomes easier, because we don't need to care about adding or removing commas

:+1:

**Comment by meaku** [comment]
I already told you my option -> TW! 
I think it looks ugly and prefer removing/adding commas whenever moving elements :)

**Comment by jhnns** [comment]
> I think it looks ugly

Very subjective. It looks unusual and there is a small learning curve (how many items has an array literal with dangling commas? 😉), but I think the benefits outweigh subjective feelings like "it's ugly".

**Comment by meaku** [comment]
>Very subjective. 

True. But code-style imposes "style" which is always subjective 😉

>how many items has an array literal with dangling commas? 😉

It does not change the `length`. So you mean the visual impact?

**Comment by flootr** [comment]
I think this rule has some advantages which are, in my sense, rather objective (point 1. and 2.) and outweigh subjective "ugliness".

**Comment by jhnns** [comment]
> But code-style imposes "style" which is always subjective

Style is not always subjective, because there are also typographic rules. But style tends to be subjective, that is true.

> It does not change the length. So you mean the visual impact?

You could think that the array has one more, `undefined` item. That's the only counter-argument I can think of.

**Comment by meaku** [comment]
You're right. Objective reasons are always more important than personal taste. With the `diff` enhancement, the objective reasons overweights my personal taste.
