### ISSUE TITLE
Change react/jsx-space-before-closing => react/jsx-tag-spacing

### ISSUE THREAD

**Issue by antosan** [peerigon/eslint-config-peerigon#13]
The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.

https://github.com/peerigon/eslint-config-peerigon/blob/5e1b859173a4fd6eaeef7b1eac71d63d8cef9261/react.js#L42

**Comment by jhnns** [comment]
Happy to accept pull-requests 😁
