### ISSUE TITLE
Allow nesting of ternaries

### ISSUE THREAD

**Issue by jhnns** [peerigon/eslint-config-peerigon#20]
We currently disallow nesting ternaries. However, ternary expressions are nicer then if-statements since they don't have the tendency to aggregate spaghetti code. A ternary expression says that `x is either y or z`. An `if` statement opens a new code branch where a lot of stuff may happen. Reasoning about code that has a lot of `if` statements that set all sorts of boolean flags can be really hard to understand.

The current rule that disallows nesting ternaries is probably just based on the unfamiliarity that a lot of developer have with ternary expressions.

However, in conjunction with a unified formatting style using prettier, nested ternary expressions can  describe more complicated control flow in a nice way, as demonstrated in this reducer:

![bildschirmfoto 2018-03-07 um 15 17 39](https://user-images.githubusercontent.com/781746/37097027-bef571cc-221a-11e8-9cb3-1d37a31743ea.jpg)

Eric Elliott recently published an article that goes in the same direction: https://medium.com/javascript-scene/nested-ternaries-are-great-361bddd0f340

We already allow nested ternary expressions in React components.

**Comment by flootr** [comment]
I find nested ternaries quite hard to read to be honest especially if they are not split up to different lines but on one line (I have seen this more often than something like you posted).

The second thing which concerns me is debugging. Is it possible to step between the conditions compared to if-statements?

I'm not necessarily against it but I found it more cumbersome in the past. Is it possible to enforce new lines like in your example?

**Comment by jhnns** [comment]
> I find nested ternaries quite hard to read to be honest especially if they are not split up to different lines but on one line (I have seen this more often than something like you posted).

Yes, nested ternaries in one line are very hard to read.

> The second thing which concerns me is debugging. Is it possible to step between the conditions compared to if-statements?

Since a ternary expression is an expression, there is nothing to step over. However:

- if there is a more complex operation going on behind the ternary expression (as in my example), you can step into the function and see which function is executed:

![bildschirmfoto 2018-03-07 um 23 08 27](https://user-images.githubusercontent.com/781746/37121272-ee1578f2-225c-11e8-9e2e-5f07667f7420.jpg)

- if the ternary expression was an assignment to a variable, the variable can be inspected afterwards

- if the ternary expression was at the end of the function (as also in my example), stepping over the expression reveals the return value in the variables explorer:

![bildschirmfoto 2018-03-07 um 23 10 13](https://user-images.githubusercontent.com/781746/37121321-0f3f4904-225d-11e8-98b9-1f2bca6a2eee.jpg)

> I'm not necessarily against it but I found it more cumbersome in the past. Is it possible to enforce new lines like in your example?

We can make it [always multiline](https://eslint.org/docs/rules/multiline-ternary). I also find that more readable.

**Comment by flootr** [comment]
Awesome @jhnns thanks 👍
