### ISSUE TITLE
no-process-exit should be a warning

### ISSUE THREAD

**Issue by jhnns** [peerigon/eslint-config-peerigon#30]
It's an error currently, but there are legitimate use cases where `process.exit()` is appropriate. 
@meaku

**Comment by meaku** [comment]
As discussed I think `process.exit(1)` should always be replaced with trowing an error. 
`process.exit(0)` on the other hand is something you should not need but sometimes it's a valid option to force shutdown the process. 

I'm fine with warning instead of error.

**Comment by jhnns** [comment]
Yes. I want to switch to warnings for all ESLint issues that have legitimate use cases.
