### ISSUE TITLE
String concat vs. Template Strings

### ISSUE THREAD

**Issue by acidicX** [peerigon/eslint-config-peerigon#4]
Paul und ich haben uns gerade entschieden, bei www das `prefer-template` zu kicken.
Irgendwie haben beide Methoden ihren Sinn, und es ist kein großer Stilbruch wenn man mal das Eine, mal das Andere nimmt.

Hier z.B. ist die normale string concat einfach viel besser lesbar:
![concat](https://cloud.githubusercontent.com/assets/1297454/12237381/ab593ba6-b87e-11e5-9d2b-1bf657ac38e2.png)

**Comment by jhnns** [comment]
Da hast du recht, ist vermutlich zu streng.

**Comment by flootr** [comment]
I prefer template strings whenever possible.

**Comment by jhnns** [comment]
Ich bin mir auch unsicher. Eigentlich denk ich da wie der Flootr.

@acidicX Ist bei dir nicht auch das Problem, dass der JavaScript-Part in der gleichen Farbe wie der String ist?

**Comment by acidicX** [comment]
Nö. Spaces machen das Ganze im Bsp einfach viel übersichtlicher und das Plus-Zeichen erschließt sich auch automatisch, weil hier in dem Sinne ja auch etwas addiert wird. Template Strings machen imho manchmal Sinn in Templates, aber sonst fast nirgendwo, weil man diesen zusätzlichen ${}-Salat hat, zusätzlich zu den anderen `()[]{}` innerhalb von normalem Code.

**Comment by jhnns** [comment]
Mit dem richtigen Theme ist das eigentlich ziemlich gut lesbar mit Template-Strings:

![bildschirmfoto 2016-07-18 um 10 48 11](https://cloud.githubusercontent.com/assets/781746/16909799/2802cec0-4cd5-11e6-9878-97f5bfb5af01.jpg)

**Comment by acidicX** [comment]
Ich finds immer noch viel schlechter lesbar als die statements oben drüber :)

**Comment by jhnns** [comment]
Die Regel ist ja schon seit Januar deaktiviert
