### ISSUE TITLE
Disable promise/prefer-await-to-then

### ISSUE THREAD

**Issue by jhnns** [peerigon/eslint-config-peerigon#61]
We currently have [`promise/prefer-await-to-then: "error"`](https://github.com/xjamundx/eslint-plugin-promise/blob/master/docs/rules/prefer-await-to-then.md) which forbids the use of `.then()` and `.catch()`. Most of the time I think this is a good rule because I think code should not switch arbitrarily between promise and async/await.

But there are situations where promise code is more elegant. Example:

```js
    useEffect(() => {
        (async () => {
            let movies;
            try {
               movies = await fetchMovies(searchPhrase);
            } catch (error) {
               handleError(error);
               return;
            }
            setMovies(movies);
        })();
    }, [fetchMovies, searchPhrase]);
```

compared to:

```js
    useEffect(() => {        
        fetchMovies(searchPhrase)
            .then(setMovies, handleError);
    }, [fetchMovies, searchPhrase]);
```

The thing is that we can't write:

```js
    useEffect(async () => {
        try {
           setMovies(await fetchMovies(searchPhrase));
        } catch (error) {
           handleError(error);
        }
    }, [fetchMovies, searchPhrase]);
```

because `useEffect()` must not return a promise (just a function) and we don't want `setMovies()` to be in the error handler.

What do you think? Should we disable it?

**Comment by meaku** [comment]
I agree! You should not switch much in your code, but there are certainly cases that require promises or might be more elegant with promises.
