### ISSUE TITLE
JSDoc Rules Performance

### ISSUE THREAD

**Issue by bytetyde** [peerigon/eslint-config-peerigon#87]
Can we please remove the js doc rules from the base package or move them in a separate opt-in config. In a default typescript project jsdoc shouldn't even be necessary but makes eslint unusable slow.
Not sure if a jsdoc update made it this worse but a normal auto fix on file save took most of the times over 20 seconds!

Running the eslint with a per-rule-performance overview results in this:

Rule                                             | Time (ms) | Relative
:------------------------------------------------|----------:|--------:
jsdoc/no-undefined-types                         | 19276.156 |    70.2%
@typescript-eslint/promise-function-async        |  1216.455 |     4.4%
jsdoc/check-examples                             |   912.954 |     3.3%
jsdoc/require-hyphen-before-param-description    |   522.048 |     1.9%
jsdoc/check-access                               |   520.341 |     1.9%
jsdoc/check-indentation                          |   343.275 |     1.3%
jsdoc/require-property-name                      |   343.237 |     1.3%
@typescript-eslint/no-unnecessary-type-arguments |   335.724 |     1.2%
jsdoc/check-property-names                       |   323.427 |     1.2%
jsdoc/require-property-type                      |   309.994 |     1.1%

vs without jsdoc

Rule                                             | Time (ms) | Relative
:------------------------------------------------|----------:|--------:
@typescript-eslint/promise-function-async        |   705.487 |    34.9%
@typescript-eslint/no-unused-vars                |   133.625 |     6.6%
@typescript-eslint/no-unnecessary-type-arguments |   132.131 |     6.5%
import/default                                   |   118.931 |     5.9%
@typescript-eslint/no-unnecessary-condition      |    80.011 |     4.0%
max-lines                                        |    63.629 |     3.1%
padding-line-between-statements                  |    45.437 |     2.2%
import/extensions                                |    44.122 |     2.2%
react/prefer-stateless-function                  |    41.522 |     2.1%
react/no-unknown-property                        |    35.161 |     1.7%

**Comment by jhnns** [comment]
Wow, 20 seconds is really slow 👀

Yes, we can move it into a separate rule config. It doesn't need to be part of the base config.

I'm still surprised to see such high numbers though. In a mid-sized project I'm currently working on the numbers are lower:

```
Rule                                      | Time (ms) | Relative
:-----------------------------------------|----------:|--------:
import/default                            |   980.433 |    12.4%
@typescript-eslint/promise-function-async |   967.349 |    12.2%
react/prefer-stateless-function           |   381.644 |     4.8%
jsdoc/no-undefined-types                  |   244.967 |     3.1%
react/no-deprecated                       |   243.917 |     3.1%
react/default-props-match-prop-types      |   222.653 |     2.8%
react/void-dom-elements-no-children       |   205.561 |     2.6%
react/no-direct-mutation-state            |   204.304 |     2.6%
@typescript-eslint/unbound-method         |   200.403 |     2.5%
jsdoc/check-access                        |   183.502 |     2.3%
```

Btw: I know that all performance numbers about rules that use the TypeScript compiler are kind of skewed. The first rule that uses TypeScript will always be reported as the slowest because it includes the TypeScript compiler startup.

Another way to speed up ESLint is to use the `--cache` flag. My numbers above are without cache.
